### ISSUE TITLE
Triple library missing

### ISSUE THREAD

**Issue by gampleman** [elmcraft/core-extra#21]
One of the types where an -extra library would be handy are triples `(a, b, c)`.

Does it make sense to add such a library? Should it go into `Tuple.Extra` or should we make a new name for it? `Triple.Extra`?

Some candidate functions:

- `triple : a -> b -> c -> (a, b, c)`
- `first : (a, b, c) -> a`
- `second : (a, b, c) -> b`
- `third : (a, b, c) -> c`
- `mapFirst`, `mapSecond`, `mapThird`
- `map : (a -> b) -> (a, a, a) -> (b, b, b)`
- `mapAll : (a -> x) -> (b -> y) -> (c -> z) -> (a, b, c) -> (x, y, z)`
- `from : a -> (a, a, a)`
- and perhaps analogues of `Tuple.Extra` functions, although perhaps we could wait for demand there...

**Comment by ahankinson** [comment]
I would vote for adding it to the existing `Tuple` library, since the data type is a tuple, just with three values (not two).

**Comment by miniBill** [comment]
I'm not unconvinced it shouldn't just be called `Triple`

**Comment by lue-bird** [comment]
(too many negations...)

**Comment by miniBill** [comment]
I think we could just call it `Triple`
