### ISSUE TITLE
`List.Extra.reverseFilter` has wrong documentation

### ISSUE THREAD

**Issue by lue-bird** [elmcraft/core-extra#37]
`List.Extra.reverseFilter` is not published in elm-community/list-extra but it is here (which is fine).
The issue is that it's documentation is copied from reverseMap and is therefore wrong: https://github.com/elmcraft/core-extra/blob/master/src/List/Extra.elm#L577

I'd suggest either removing the added, non-published helper or correcting the documentation.

**Comment by gampleman** [comment]
I'd be for removing it myself.
