### ISSUE TITLE
Incorporating `elm-community/html-extra`?

### ISSUE THREAD

**Issue by SiriusStarr** [elmcraft/core-extra#43]
If the goal of this is to subsume elm-community, [html-extra](https://package.elm-lang.org/packages/elm-community/html-extra/latest/) is currently missing.  Or was there a choice made to exclude it to avoid a dependency on `elm/html`?

**Comment by gampleman** [comment]
The scope is at the moment limited to functions oriented around the types from elm/core, hence core-extra. It’s already a very large library and I’d rather not take a bite I can’t chew :)

In general I think the continuity plan for the rest of elm-community is as before - it’s waiting for individuals to step up and fork.
