### ISSUE TITLE
Transfer documenting issues from old libraries?

### ISSUE THREAD

**Issue by jmbromley** [elmcraft/core-extra#44]
Some issues in the old elm-community libraries were not fixed because they addressed corner-cases or other niche areas that weren't deemed mainstream enough.  However these issues were left open to maintain a documented record of the problem and possible workaround in case others should encounter them.  I suppose you could call them 'documenting issues'.

Are there any plans to 'migrate' these issue over to core-extra so they can be easily found by those who come looking?

An example is the following bug report of mine for list-extra which took me quite a bit of digging to get to the bottom of and so I think could be useful to preserve for future users who might run up against it:

 https://github.com/elm-community/list-extra/issues/164

**Comment by gampleman** [comment]
We've merged some of the open PRs on some of those repositories already, but apart from that I don't particularly intend to do any issue transfers. It's a very large amount of work and I'm skeptical about the payoff. 

Personally I'd rather add a short note to the documentation perhaps with a link to the original issue.

**Comment by jmbromley** [comment]
@gampleman  Okay, I've made a PR (#46) to put a note in the documentation as you suggest for the example I cited.
