### ISSUE TITLE
Renaming things, removing things

### ISSUE THREAD

**Issue by miniBill** [elmcraft/core-extra#5]
While I think that we should remove and rename some cruft, I think we should _not_ do it in the 1.0 release, because otherwise it would make it really hard for big projects to switch.

I think the best plan is to have a v1 with the all the existing APIs, but adding the new ones with better names and then "immediately" release 2.0.0 with the uniform names only.

Imagine you have a project with 50 different people working on it, there is no way you'll be able to land a PR switching to core-extra if you can't do it incrementally!

[tagging @gampleman and @Luftzig]

**Comment by supermario** [comment]
Nerd sniping @MartinSStewart / @jfmengels into doing/sharing the elm-review rewrite rule magic for automatically helping people upgrade API name changes 😀

**Comment by miniBill** [comment]
Shouldn't be super hard? Find leaves, resolve module, `case (moduleName, name)` and then just replace the function name, or just an error if it's been deprecated without a replacement

**Comment by gampleman** [comment]
OK, I think I'm mostly aboard with this plan with some exceptions. The `Order.Extra` is already a fair bit different than elm-ordering, so I would suggest that there backwards compatibility will be on a best effort basis. Other than that, we should already mark the old versions as deprecated.

**Comment by gampleman** [comment]
One further thought that we should decide on:

What about things where we want to keep the name

1. and want to (significantly) change behavior?
2. and what to change the type signature?

I think 2 should be fine in v2.0, but perhaps trickier to do an automated migration (but at least the compiler will pick it up).

For 1, we can either make a policy of just not doing that. Alternatively if the list is small, perhaps it will be fine with release notes?

---

On an unrelated note, I think we're roughly in shape now where we've got all the functionality in, the build passing and some improvements made. I think now we can start making backwards compatible changes (and adding @deprecated comments, etc). Once we're reasonably happy there, I'l make a `v2` branch where we can start the process of removing the deprecated cruft and building the migration tool.

Does that sound reasonable?
