### ISSUE TITLE
Add Dict.Extra.updateIfExists 

### ISSUE THREAD

**Issue by gampleman** [elmcraft/core-extra#58]
## `Dict.Extra.updateIfExists : comparable -> (a -> a) -> Dict comparable a -> Dict comparable a`

Updates a value if the key is present in the dictionary, leaves the dictionary untouched otherwise.

### Motivating use case 

Dict.update has an overly complex signature for many use cases. It's fairly common to combine it with `Maybe.map`, but this adds a fair amount of noise in code.

**Comment by miniBill** [comment]
(Considering how `update` is implemented, this should be implemented via `get`/`if`/`insert` and not `update (Maybe.map)`)
